# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: transport/webcast/im.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto


class PayloadInImCompressTypeEnum(betterproto.Enum):
    NONE = 0
    ZLIB = 1
    ZSTD = 2


@dataclass(eq=False, repr=False)
class Message(betterproto.Message):
    method: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)
    msg_id: int = betterproto.int64_field(3)
    msg_type: int = betterproto.int32_field(4)
    offset: int = betterproto.int64_field(5)
    need_wrds_store: bool = betterproto.bool_field(6)
    wrds_version: int = betterproto.int64_field(7)
    wrds_sub_key: str = betterproto.string_field(8)
    message_extra: Dict[str, str] = betterproto.map_field(
        9, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    tenant_id: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class PayloadInIm(betterproto.Message):
    payloads: Dict[str, bytes] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_BYTES
    )
    compress_type: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class PreviewHistoryResponse(betterproto.Message):
    data: "PreviewHistoryResponseResponseData" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PreviewHistoryResponseResponseData(betterproto.Message):
    messages: List["Message"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class PushFrame(betterproto.Message):
    seq_id: int = betterproto.uint64_field(1)
    log_id: int = betterproto.uint64_field(2)
    service: int = betterproto.int32_field(3)
    method: int = betterproto.int32_field(4)
    headers: List["PushHeader"] = betterproto.message_field(5)
    payload_encoding: str = betterproto.string_field(6)
    payload_type: str = betterproto.string_field(7)
    payload: bytes = betterproto.bytes_field(8)
    lod_id_new: str = betterproto.string_field(9)


@dataclass(eq=False, repr=False)
class PushHeader(betterproto.Message):
    key: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Request(betterproto.Message):
    live_id: int = betterproto.int64_field(1)
    aid: int = betterproto.int64_field(2)
    room_id: str = betterproto.string_field(3)
    identity: str = betterproto.string_field(4)
    last_rtt: str = betterproto.string_field(5)
    internal_ext: str = betterproto.string_field(6)
    cursor: str = betterproto.string_field(7)
    device_id: str = betterproto.string_field(8)
    unique_id: str = betterproto.string_field(9)
    device_platform: str = betterproto.string_field(10)
    app_language: str = betterproto.string_field(11)
    version_code: str = betterproto.string_field(12)
    update_version_code: str = betterproto.string_field(13)
    resp_content_type: str = betterproto.string_field(14)
    get_history: str = betterproto.string_field(15)
    ac: str = betterproto.string_field(16)
    keep_method: str = betterproto.string_field(17)
    stress: str = betterproto.string_field(18)
    recv_cnt: int = betterproto.int64_field(19)
    parse_cnt: int = betterproto.int64_field(20)
    fetch_rule: str = betterproto.string_field(21)
    ab_group: str = betterproto.string_field(22)
    live_cursor: str = betterproto.string_field(23)
    sub_room_id: str = betterproto.string_field(24)
    need_persist_msg_count: int = betterproto.int64_field(25)


@dataclass(eq=False, repr=False)
class Response(betterproto.Message):
    messages: List["Message"] = betterproto.message_field(1)
    cursor: str = betterproto.string_field(2)
    fetch_interval: int = betterproto.int64_field(3)
    now: int = betterproto.int64_field(4)
    internal_ext: str = betterproto.string_field(5)
    fetch_type: int = betterproto.int32_field(6)
    route_params: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    heartbeat_duration: int = betterproto.int64_field(8)
    need_ack: bool = betterproto.bool_field(9)
    push_server: str = betterproto.string_field(10)
    live_cursor: str = betterproto.string_field(11)
    history_no_more: bool = betterproto.bool_field(12)
    proxy_server: str = betterproto.string_field(13)
    push_server_v2: str = betterproto.string_field(14)
