# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: bizIm/live.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto


@dataclass(eq=False, repr=False)
class AtmosphereData(betterproto.Message):
    img: str = betterproto.string_field(1)
    num: str = betterproto.string_field(2)
    bg_color: str = betterproto.string_field(3)
    border_color: str = betterproto.string_field(4)
    left_margin: int = betterproto.int64_field(5)
    bg_colors: List[str] = betterproto.string_field(6)
    border_colors: List[str] = betterproto.string_field(7)
    top_img: str = betterproto.string_field(8)
    bg_img: "UrlPicture" = betterproto.message_field(9)
    left_icon: "UrlPicture" = betterproto.message_field(10)


@dataclass(eq=False, repr=False)
class AuctionAtmosphere(betterproto.Message):
    count_down: "CountdownAtmosphere" = betterproto.message_field(1)
    digital: "DigitalAtmosphere" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AuctionInfo(betterproto.Message):
    price: int = betterproto.int64_field(1)
    price_label: str = betterproto.string_field(2)
    status: int = betterproto.int32_field(3)
    jump_url: str = betterproto.string_field(4)
    current_user_info: "CurrentUserInfo" = betterproto.message_field(5)
    incr_price_lists: List["IncrPriceList"] = betterproto.message_field(6)
    button_label: str = betterproto.string_field(7)
    product_id: int = betterproto.int64_field(8)
    end_time: int = betterproto.int64_field(9)
    biz_id: int = betterproto.int32_field(10)


@dataclass(eq=False, repr=False)
class AuctionSuccess(betterproto.Message):
    title: str = betterproto.string_field(1)
    product_id: int = betterproto.int64_field(2)
    product_name: str = betterproto.string_field(3)
    product_pic: str = betterproto.string_field(4)
    price: int = betterproto.int64_field(5)
    charge: int = betterproto.int64_field(6)
    freight: int = betterproto.int64_field(7)
    total: int = betterproto.int64_field(8)
    button_label: str = betterproto.string_field(9)
    jump_url: str = betterproto.string_field(10)
    freight_collect: str = betterproto.string_field(11)
    left_payment_time: int = betterproto.int64_field(12)
    biz_id: int = betterproto.int32_field(13)
    deposit_info: str = betterproto.string_field(14)


@dataclass(eq=False, repr=False)
class AuctionUpdateMessage(betterproto.Message):
    product_id: int = betterproto.int64_field(1)
    auction_id: int = betterproto.int64_field(2)
    action_type: int = betterproto.int32_field(3)
    jump_schema: str = betterproto.string_field(4)
    end_time_refresh_info: "AuctionUpdateMessageEndTimeRefreshInfo" = (
        betterproto.message_field(5)
    )
    price_refresh_info: str = betterproto.string_field(6)
    pre_bid_refresh_info: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class AuctionUpdateMessageEndTimeRefreshInfo(betterproto.Message):
    end_time: int = betterproto.int64_field(1)
    toast: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class AuthorConnectMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    toast: str = betterproto.string_field(2)
    ecom_linkmic_room_ids: List[int] = betterproto.int64_field(3)
    linkmic_pop_rooms: List["ConnectRoom"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class AuthorOrderLimitInfo(betterproto.Message):
    icon: "Icon" = betterproto.message_field(1)
    title: str = betterproto.string_field(2)
    content: str = betterproto.string_field(3)
    button: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class BarrageBuyInfo(betterproto.Message):
    nick_name: str = betterproto.string_field(1)
    purchase_cnt: int = betterproto.int64_field(2)
    text: str = betterproto.string_field(3)
    icon: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class BenefitLabel(betterproto.Message):
    left_text: str = betterproto.string_field(1)
    right_text: str = betterproto.string_field(2)
    text_style: int = betterproto.int32_field(3)
    color_style: int = betterproto.int32_field(4)
    div_line: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class BidInfo(betterproto.Message):
    promotion_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class BizActionMeta(betterproto.Message):
    action_name: str = betterproto.string_field(1)
    action_param: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class BrowseInfo(betterproto.Message):
    duration: int = betterproto.int32_field(1)
    task_index: str = betterproto.string_field(2)
    stop_duration: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class CategoryInfo(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)
    promotion_ids: List[str] = betterproto.string_field(3)
    type: str = betterproto.string_field(4)
    unique_index: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class CategoryRefreshMessage(betterproto.Message):
    category_info: List["CategoryRefreshMessageCategoryInfo"] = (
        betterproto.message_field(1)
    )
    update_ts: int = betterproto.int64_field(2)
    update_toast: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CategoryRefreshMessageCategoryInfo(betterproto.Message):
    unique_index: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    category_id: int = betterproto.int64_field(3)
    category_type: int = betterproto.int64_field(4)
    need_reload: bool = betterproto.bool_field(5)
    disable_append: bool = betterproto.bool_field(6)


@dataclass(eq=False, repr=False)
class ConnectRoom(betterproto.Message):
    room_id: int = betterproto.int64_field(1)
    author_id: int = betterproto.int64_field(2)
    sec_author_id: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class CountdownAtmosphere(betterproto.Message):
    start_time: int = betterproto.int64_field(1)
    end_time: int = betterproto.int64_field(2)
    data: "AtmosphereData" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class CouponActivityInfoMessage(betterproto.Message):
    activity_type: int = betterproto.int64_field(1)
    before_text: str = betterproto.string_field(2)
    before_button: str = betterproto.string_field(3)
    after_text: str = betterproto.string_field(4)
    after_button: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class CouponInfo(betterproto.Message):
    meta_id: int = betterproto.int64_field(1)
    server_time: int = betterproto.int64_field(2)
    countdown: int = betterproto.int64_field(3)
    activity_json_str: str = betterproto.string_field(4)
    coupon_type: int = betterproto.int32_field(5)
    activity_info: "CouponActivityInfoMessage" = betterproto.message_field(6)
    coupon_meta: "CouponMetaInfoMessage" = betterproto.message_field(7)
    meta_id_str: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class CouponMetaInfoMessage(betterproto.Message):
    coupon_meta_id: str = betterproto.string_field(1)
    start_time: str = betterproto.string_field(2)
    expire_time: str = betterproto.string_field(3)
    period_type: int = betterproto.int64_field(4)
    valid_period: int = betterproto.int64_field(5)
    start_apply_time: str = betterproto.string_field(6)
    end_apply_time: str = betterproto.string_field(7)
    coupon_name: str = betterproto.string_field(8)
    url: str = betterproto.string_field(9)
    threshold: int = betterproto.int64_field(10)
    credit: int = betterproto.int64_field(11)
    max_apply_times: int = betterproto.int64_field(12)
    type: int = betterproto.int64_field(13)
    type_detail: str = betterproto.string_field(14)
    discount: float = betterproto.double_field(15)
    shop_id: str = betterproto.string_field(16)
    pay_type: int = betterproto.int64_field(17)
    max_discount_limit: int = betterproto.int64_field(18)
    shop_name: str = betterproto.string_field(19)
    type_string: str = betterproto.string_field(20)
    what_coupon: str = betterproto.string_field(21)
    coupon_string: str = betterproto.string_field(22)
    channel_id: int = betterproto.int64_field(23)
    left_amount: int = betterproto.int64_field(24)
    has_applied: int = betterproto.int64_field(25)
    status: int = betterproto.int64_field(26)
    shop_logo: str = betterproto.string_field(27)
    is_show: int = betterproto.int64_field(28)
    total_amount: int = betterproto.int64_field(29)
    live_coupon_status: int = betterproto.int32_field(30)
    coupon_source: int = betterproto.int32_field(31)
    user_apply_times: int = betterproto.int64_field(32)
    can_continue_apply: bool = betterproto.bool_field(33)
    coupon_status: bool = betterproto.bool_field(34)
    coupon_reset: bool = betterproto.bool_field(35)
    start_time_timestamp: int = betterproto.int64_field(36)
    expire_time_timestamp: int = betterproto.int64_field(37)
    avatar: str = betterproto.string_field(38)
    kol_uid: int = betterproto.int64_field(39)
    product_ids: List[int] = betterproto.int64_field(40)
    platform_sub_type: int = betterproto.int64_field(41)
    has_available_goods: bool = betterproto.bool_field(42)
    type_title: str = betterproto.string_field(43)
    kol_user_tag: int = betterproto.int64_field(45)
    type_icon: str = betterproto.string_field(46)
    type_icon_width: int = betterproto.int64_field(47)
    type_icon_height: int = betterproto.int64_field(48)
    coupon_category: str = betterproto.string_field(49)
    extra_data: str = betterproto.string_field(50)


@dataclass(eq=False, repr=False)
class CurrentUserInfo(betterproto.Message):
    user_pic: "Img" = betterproto.message_field(1)
    user_name: str = betterproto.string_field(2)
    user_id: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class DelayParam(betterproto.Message):
    delay_strategy: int = betterproto.int32_field(1)
    min_delay_ms: int = betterproto.int32_field(2)
    max_delay_ms: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class DigitalAtmosphere(betterproto.Message):
    frequency_key: str = betterproto.string_field(1)
    frequency_count: int = betterproto.int64_field(2)
    data: "AtmosphereData" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ElementAvatar(betterproto.Message):
    avatar: "UrlImage" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ElementBlank(betterproto.Message):
    width: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class ElementImage(betterproto.Message):
    image: "UrlImage" = betterproto.message_field(1)
    bubble: "ElementImageBubble" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ElementImageBubble(betterproto.Message):
    height: int = betterproto.int64_field(1)
    border_radius: int = betterproto.int64_field(2)
    background_color: str = betterproto.string_field(3)
    border_color: str = betterproto.string_field(4)
    text: str = betterproto.string_field(5)
    font_size: int = betterproto.int64_field(6)
    color: str = betterproto.string_field(7)
    horizontal_padding: int = betterproto.int64_field(8)


@dataclass(eq=False, repr=False)
class ElementLoopText(betterproto.Message):
    texts: List[str] = betterproto.string_field(1)
    color: str = betterproto.string_field(2)
    size: int = betterproto.int64_field(3)
    bold: bool = betterproto.bool_field(4)
    anim_gap: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class ElementText(betterproto.Message):
    text: str = betterproto.string_field(1)
    color: str = betterproto.string_field(2)
    size: int = betterproto.int64_field(3)
    bold: bool = betterproto.bool_field(4)
    background: "UrlImage" = betterproto.message_field(5)
    max_width: int = betterproto.int64_field(6)
    ellipsis: bool = betterproto.bool_field(7)


@dataclass(eq=False, repr=False)
class FilterSwitchChangeData(betterproto.Message):
    enable: bool = betterproto.bool_field(1)
    up_icon: "UpIcon" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class GmvData(betterproto.Message):
    gmv: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class HotAtmosphere(betterproto.Message):
    img: str = betterproto.string_field(1)
    sale_num: str = betterproto.string_field(2)
    type: int = betterproto.int64_field(3)
    num: str = betterproto.string_field(4)
    bg_color: str = betterproto.string_field(5)
    border_color: str = betterproto.string_field(6)
    left_margin: int = betterproto.int64_field(7)
    ui_type: int = betterproto.int64_field(8)
    bg_colors: List[str] = betterproto.string_field(9)
    border_colors: List[str] = betterproto.string_field(10)
    top_img: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class Icon(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    width: int = betterproto.int32_field(2)
    height: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class Img(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    height: int = betterproto.int32_field(2)
    width: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class IncrPriceList(betterproto.Message):
    price: int = betterproto.int64_field(1)
    range: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class IntelligentPopMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    bubble_type: int = betterproto.int32_field(2)
    promotion_id: int = betterproto.int64_field(3)
    delay_param: "DelayParam" = betterproto.message_field(4)
    params: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    list_top_path: str = betterproto.string_field(10)
    pop_path: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class InteractionAvatar(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    width: int = betterproto.int32_field(2)
    height: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class InteractionContent(betterproto.Message):
    check: "InteractionContentCheck" = betterproto.message_field(1)
    priority: int = betterproto.int32_field(2)
    loop_count: int = betterproto.int32_field(3)
    content: List["InteractionElement"] = betterproto.message_field(4)
    event_param: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    rows: List["ListTopInteractionRow"] = betterproto.message_field(6)
    bg_colors: List[str] = betterproto.string_field(7)
    product: "MessageProduct" = betterproto.message_field(8)
    action: "ListAction" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class InteractionContentCheck(betterproto.Message):
    product_id: int = betterproto.int64_field(1)
    index: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class InteractionData(betterproto.Message):
    full: bool = betterproto.bool_field(1)
    contents: List["InteractionContent"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class InteractionElement(betterproto.Message):
    element_type: int = betterproto.int32_field(1)
    text: str = betterproto.string_field(2)
    text_color: str = betterproto.string_field(3)
    avatars: "InteractionAvatar" = betterproto.message_field(4)
    blank_width: int = betterproto.int32_field(5)
    text_size: int = betterproto.int32_field(6)
    text_v2: "ElementText" = betterproto.message_field(20)
    blank_v2: "ElementBlank" = betterproto.message_field(21)
    avatars_v2: "ElementAvatar" = betterproto.message_field(23)
    image_v2: "ElementImage" = betterproto.message_field(24)
    loop_text: "ElementLoopText" = betterproto.message_field(29)


@dataclass(eq=False, repr=False)
class JumpActionMeta(betterproto.Message):
    url: str = betterproto.string_field(1)
    append_params_type: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class JumpUrl(betterproto.Message):
    key: str = betterproto.string_field(1)
    text: str = betterproto.string_field(2)
    url: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ListAction(betterproto.Message):
    action_type: int = betterproto.int64_field(1)
    biz_action: "BizActionMeta" = betterproto.message_field(2)
    jump_action: "JumpActionMeta" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ListTopInteractionRow(betterproto.Message):
    content: List["InteractionElement"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class LiveCommonMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    screenshot_timestamp: int = betterproto.int64_field(2)
    room_tag_offline_info: "RoomTagOfflineInfo" = betterproto.message_field(3)
    filter_switch_change_data: "FilterSwitchChangeData" = betterproto.message_field(4)
    gmv_data: "GmvData" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class LiveHighHeatMessage(betterproto.Message):
    redirect_data: "RedirectData" = betterproto.message_field(1)
    route_rule: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class LiveInteractionMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    barrage_buy_info: "BarrageBuyInfo" = betterproto.message_field(2)
    interaction_data: "InteractionData" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class LiveMarketingMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    product_ids: List[int] = betterproto.int64_field(2)
    auction_success: "AuctionSuccess" = betterproto.message_field(3)
    auction_info: "AuctionInfo" = betterproto.message_field(4)
    redpack_activity_info: "RedpackActivityInfo" = betterproto.message_field(5)
    win_lotteryinfo: "WinLotteryInfo" = betterproto.message_field(6)
    lottery_info_list: "LotteryInfoList" = betterproto.message_field(7)
    coupon_info: "CouponInfo" = betterproto.message_field(8)
    task_info: "TaskInfo" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class LivePopMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    bubble_type: int = betterproto.int32_field(2)
    promotion_id: int = betterproto.int64_field(3)
    hot_atmosphere: "HotAtmosphere" = betterproto.message_field(4)
    delay_param: "DelayParam" = betterproto.message_field(5)
    product_info: "PopProductInfo" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class LiveSellerMessage(betterproto.Message):
    msg_type: int = betterproto.int32_field(1)
    author_order_limit_info: "AuthorOrderLimitInfo" = betterproto.message_field(2)
    list_room_stats_data: List["StatsData"] = betterproto.message_field(3)
    flash_popup_info: "PopupInfo" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class LiveTargetFlashMessage(betterproto.Message):
    schema: str = betterproto.string_field(1)
    create_time: int = betterproto.int64_field(2)
    promotion_id: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class LotteryInfoList(betterproto.Message):
    activity_id: str = betterproto.string_field(1)
    task_type: int = betterproto.int64_field(2)
    open_time: int = betterproto.int64_field(3)
    user_activity_status: int = betterproto.int64_field(4)
    win_record_id: str = betterproto.string_field(5)
    result_label: str = betterproto.string_field(6)
    button_label: str = betterproto.string_field(7)
    text: List[str] = betterproto.string_field(8)
    jump_url: str = betterproto.string_field(9)
    lottery_type: int = betterproto.int64_field(10)
    elastic_title: str = betterproto.string_field(11)
    benefit_label: "BenefitLabel" = betterproto.message_field(12)
    extra_info: str = betterproto.string_field(99)


@dataclass(eq=False, repr=False)
class MessageProduct(betterproto.Message):
    cover: "ProductCover" = betterproto.message_field(1)
    show_index: bool = betterproto.bool_field(2)
    index: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class PopProductInfo(betterproto.Message):
    promotion_id: int = betterproto.int64_field(1)
    product_id: int = betterproto.int64_field(2)
    explain_time: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class PopupInfo(betterproto.Message):
    title: str = betterproto.string_field(1)
    text: str = betterproto.string_field(2)
    urls: List["JumpUrl"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ProductAtmosphere(betterproto.Message):
    atmosphere_type: int = betterproto.int32_field(1)
    num_atmosphere: "ProductNumAtmosphere" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ProductCover(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    width: int = betterproto.int64_field(2)
    height: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class ProductInfo(betterproto.Message):
    promotion_id: int = betterproto.int64_field(1)
    index: int = betterproto.int32_field(2)
    target_flash_uids: List[int] = betterproto.int64_field(3)
    explain_type: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class ProductListRefreshMessage(betterproto.Message):
    update_ts: int = betterproto.int64_field(1)
    update_toast: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ProductListUpdateMessage(betterproto.Message):
    update_timestamp: int = betterproto.int64_field(1)
    update_toast: str = betterproto.string_field(2)
    update_product_info: List["ProductInfo"] = betterproto.message_field(3)
    total: int = betterproto.int64_field(4)
    update_category_info: List["CategoryInfo"] = betterproto.message_field(5)
    msg_type: int = betterproto.int32_field(6)


@dataclass(eq=False, repr=False)
class ProductNumAtmosphere(betterproto.Message):
    left_icon: "UrlPicture" = betterproto.message_field(1)
    background: "UrlPicture" = betterproto.message_field(2)
    type: int = betterproto.int64_field(3)
    num: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ProductRefreshMessage(betterproto.Message):
    promotion_id: int = betterproto.int64_field(1)
    product_id: int = betterproto.int64_field(2)
    channel_type: int = betterproto.int64_field(3)
    channel_id: int = betterproto.int64_field(4)
    update_ts: int = betterproto.int64_field(5)
    action_type: int = betterproto.int32_field(6)
    request_info: "ProductRefreshMessageRequestInfo" = betterproto.message_field(7)
    product_info: "ProductRefreshMessageProductInfo" = betterproto.message_field(8)
    hot_atmosphere: "HotAtmosphere" = betterproto.message_field(9)
    auction_info: "ProductRefreshMessageAuctionInfo" = betterproto.message_field(10)
    auction_atmosphere: "AuctionAtmosphere" = betterproto.message_field(11)
    atmosphere_info: "ProductRefreshMessageAtmosphereInfo" = betterproto.message_field(
        12
    )


@dataclass(eq=False, repr=False)
class ProductRefreshMessageRequestInfo(betterproto.Message):
    list: Dict[int, "ProductRefreshMessageRequestInfoRequest"] = betterproto.map_field(
        1, betterproto.TYPE_INT32, betterproto.TYPE_MESSAGE
    )
    pop: Dict[int, "ProductRefreshMessageRequestInfoRequest"] = betterproto.map_field(
        2, betterproto.TYPE_INT32, betterproto.TYPE_MESSAGE
    )
    intro: Dict[int, "ProductRefreshMessageRequestInfoRequest"] = betterproto.map_field(
        3, betterproto.TYPE_INT32, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class ProductRefreshMessageRequestInfoRequest(betterproto.Message):
    path: str = betterproto.string_field(1)
    params: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    delay_param: "DelayParam" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ProductRefreshMessageProductInfo(betterproto.Message):
    title: str = betterproto.string_field(1)
    cover: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ProductRefreshMessageAuctionInfo(betterproto.Message):
    price: int = betterproto.int64_field(1)
    price_label: str = betterproto.string_field(2)
    auction_atmosphere: "AuctionAtmosphere" = betterproto.message_field(3)
    end_time: int = betterproto.int64_field(4)
    current_user: "ProductRefreshMessageAuctionInfoAuctionUser" = (
        betterproto.message_field(5)
    )
    intro_price_label: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ProductRefreshMessageAuctionInfoAuctionUser(betterproto.Message):
    is_self: bool = betterproto.bool_field(1)
    name: str = betterproto.string_field(2)
    profile: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ProductRefreshMessageAtmosphereInfo(betterproto.Message):
    atmosphere: Dict[int, "ProductAtmosphere"] = betterproto.map_field(
        1, betterproto.TYPE_INT32, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class ProductUpdateMessage(betterproto.Message):
    updated_product_ids: List[int] = betterproto.int64_field(1)
    update_type: int = betterproto.int32_field(2)
    promotion_id: int = betterproto.int64_field(3)
    updated_product_info: "UpdatedProductInfo" = betterproto.message_field(4)
    sold_out: bool = betterproto.bool_field(5)
    updated_coupon_info: "UpdatedCouponInfo" = betterproto.message_field(6)
    updated_campaign_info: "UpdatedCampaignInfo" = betterproto.message_field(7)
    update_timestamp: int = betterproto.int64_field(8)
    update_sku_info: "UpdatedSkuInfo" = betterproto.message_field(9)
    updated_commentary_video_info: "UpdatedCommentaryVideoInfo" = (
        betterproto.message_field(10)
    )
    updated_group_info: "UpdatedGroupInfo" = betterproto.message_field(11)
    hot_atmosphere: "HotAtmosphere" = betterproto.message_field(12)
    can_sold: bool = betterproto.bool_field(13)
    promotion_header_interaction: "InteractionData" = betterproto.message_field(14)
    bid_info: "BidInfo" = betterproto.message_field(15)


@dataclass(eq=False, repr=False)
class RedirectData(betterproto.Message):
    route: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class RedpackActivityInfo(betterproto.Message):
    redpack_type: int = betterproto.int64_field(1)
    redpack_activity_id: str = betterproto.string_field(2)
    redpack_activity_name: str = betterproto.string_field(3)
    start_apply_time: int = betterproto.int64_field(4)
    end_apply_time: int = betterproto.int64_field(5)
    preheat_time: int = betterproto.int64_field(6)
    total_amount: int = betterproto.int64_field(7)
    author_avatar_url: str = betterproto.string_field(8)
    author_name: str = betterproto.string_field(9)
    pendant_background_url: str = betterproto.string_field(10)
    redpack_front_background_url: str = betterproto.string_field(11)
    redpack_label: str = betterproto.string_field(12)
    redpack_after_background_url: str = betterproto.string_field(13)
    redpack_after_belt_url: str = betterproto.string_field(14)
    scatter_time: int = betterproto.int64_field(15)
    server_time: int = betterproto.int64_field(16)
    max_amount: int = betterproto.int64_field(17)
    show_type: int = betterproto.int64_field(18)
    shorttouch_pendant_background_url: str = betterproto.string_field(19)
    shorttouch_pendant_icon_url: str = betterproto.string_field(20)
    shorttouch_lottie_url: str = betterproto.string_field(21)


@dataclass(eq=False, repr=False)
class RoomTagOfflineInfo(betterproto.Message):
    tag_type: int = betterproto.int64_field(1)
    user_toast: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SkuInfo(betterproto.Message):
    sku_id: str = betterproto.string_field(1)
    stock_num: int = betterproto.int64_field(2)
    price: int = betterproto.int64_field(3)
    coupon_price: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class StatsData(betterproto.Message):
    value: str = betterproto.string_field(1)
    unit: str = betterproto.string_field(2)
    type: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class TaskInfo(betterproto.Message):
    task_type: int = betterproto.int32_field(1)
    task_status: int = betterproto.int32_field(2)
    report_event: str = betterproto.string_field(3)
    browse_task_info: "BrowseInfo" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class UrlPicture(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    width: int = betterproto.int64_field(2)
    height: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class UpIcon(betterproto.Message):
    name: str = betterproto.string_field(1)
    up_icon: str = betterproto.string_field(2)
    up_desc: str = betterproto.string_field(3)
    public_screen_notice: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class UpdatedCampaignInfo(betterproto.Message):
    is_valid: bool = betterproto.bool_field(1)
    label: str = betterproto.string_field(2)
    price: str = betterproto.string_field(3)
    pic: str = betterproto.string_field(4)
    start_time: str = betterproto.string_field(5)
    end_time: str = betterproto.string_field(6)
    time_start_label: str = betterproto.string_field(7)
    time_end_label: str = betterproto.string_field(8)
    user_limit: str = betterproto.string_field(9)
    is_preheat: str = betterproto.string_field(10)
    campaign_id: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class UpdatedCommentaryVideoInfo(betterproto.Message):
    action: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class UpdatedCouponInfo(betterproto.Message):
    tag: str = betterproto.string_field(1)
    coupon_url: str = betterproto.string_field(2)
    coupon_applet: str = betterproto.string_field(3)
    is_valid: bool = betterproto.bool_field(4)
    coupon_meta_id: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class UpdatedGroupInfo(betterproto.Message):
    avatar_list: List[str] = betterproto.string_field(1)
    joined: int = betterproto.int64_field(2)
    group_size: int = betterproto.int64_field(3)
    persent: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class UpdatedProductInfo(betterproto.Message):
    price: int = betterproto.int64_field(1)
    title: str = betterproto.string_field(2)
    cover: str = betterproto.string_field(3)
    status: int = betterproto.int64_field(4)
    pop_upicon: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class UpdatedSkuInfo(betterproto.Message):
    skus: Dict[str, "SkuInfo"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    min_price: int = betterproto.int64_field(2)
    max_price: int = betterproto.int64_field(3)
    unuse_min_price: int = betterproto.int64_field(4)
    coupon_price: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class UrlImage(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    width: int = betterproto.int64_field(2)
    height: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class WinLotteryAlert(betterproto.Message):
    title: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)
    button_label: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class WinLotteryInfo(betterproto.Message):
    title: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    img: str = betterproto.string_field(3)
    button_label: str = betterproto.string_field(4)
    win_record_id: str = betterproto.string_field(5)
    activity_id: str = betterproto.string_field(6)
    is_addressed: bool = betterproto.bool_field(7)
    alert: "WinLotteryAlert" = betterproto.message_field(8)
    is_win: bool = betterproto.bool_field(9)
    jump_url: str = betterproto.string_field(10)
    product_id: int = betterproto.int64_field(11)
    activity_price: List[int] = betterproto.int64_field(12)
    buy_time: int = betterproto.int64_field(13)
    lottery_type: int = betterproto.int64_field(14)
    product_id_str: str = betterproto.string_field(15)
    lottery_info_list: "LotteryInfoList" = betterproto.message_field(16)
    draw_prize_type: int = betterproto.int64_field(17)
    button_bottom_desc: str = betterproto.string_field(18)
    extra_info: str = betterproto.string_field(99)
